config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # resources :users, only: [:show]
  #devise_for :users, controllers: { sessions: 'users/sessions' }
  get'/posts' , to: 'posts#all_posts' , as: 'all_posts'
  root  to:'topics#index'
  resources :topics do
    resources :posts do
      patch 'mark_as_read', on: :member
      resources :comments do
        resources :user_comment_ratings
      end
      resources :ratings, only: [:create]
    end
  end
  resources :tags do
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post ,counter_cache: true
  belongs_to :user
  has_one :topic, through: :post
  has_many :user_comment_ratings, dependent: :destroy
  has_many :rating_users, through: :user_comment_ratings, source: :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic
  before_action :set_post
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  include CanCan::ControllerAdditions
  load_and_authorize_resource
  # GET /comments or /comments.json
  def index
    @topic =Topic.find(params[:topic_id])
    @post=@topic.posts.find(params[:post_id])
    @comments=@post.comments
    @ratings = Comment.joins(:user_comment_ratings).distinct
  end

  # GET /comments/1 or /comments/1.json
  def show
     @ratings = @comment.user_comment_ratings
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end
  def ratings
    @comment = Comment.find(params[:id])
    @ratings = @comment.user_comment_ratings
  end
  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  # def create
  #   @comment = @post.comments.new(comment_params)
  #   @comment.topic = @topic
  #
  #   respond_to do |format|
  #     if @comment.save
  #       format.html { redirect_to topic_post_url(@topic, @post), notice: 'Comment was successfully created.' }
  #     else
  #       format.html { render :new }
  #     end
  #   end
  # end
  def create
  # @topic = Topic.find(params[:topic_id])
  # @post = @topic.posts.find(params[:post_id])
  # @comment = @post.comments.new(comment_params)
  @topic = Topic.find(params[:topic_id])
  @post = @topic.posts.find(params[:post_id])
  @comment = @post.comments.build(comment_params)
  @comment.user = current_user

  respond_to do |format|
    if @comment.save
      format.html { redirect_to params[:referrer] || topic_post_comments_url(@topic, @post), notice: 'Comment was successfully created.' }
    else
      format.html { render :new }
    end
  end
end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.find(params[:post_id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to params[:referrer] || topic_post_comment_url(@topic, @post), notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy

    @comment.destroy
    respond_to do |format|
      format.html { redirect_to params[:referrer] || topic_post_comments_url(@topic, @post), notice: 'Comment was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_post
    @post = @topic.posts.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:post_id,:referrer , :text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_for([@topic,@post,@comment]) do |form| %>
  <%= hidden_field_tag :referrer, request.referer %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:
      </h2>

      <ul>
        <% @comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :post_id %>

  <%= form.label :text, "Text:" %>
  <%= form.text_area :text %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <% link_to "Show this comment", topic_post_comment_path(@topic, @post, @comment) %>
  <%= link_to "Back to comments", topic_post_comments_path(@topic,@post,@comment), class: "btn btn-secondary" %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments in <%= @post.title %></h1>

<%= link_to "New comment", new_topic_post_comment_path(@topic, @post) %>
<br>
<br>

<div id="comments">
  <% if @comments.any? %>
    <table style="width:100%">
      <thead>
      <tr>
        <th>Comments</th>
        <th>User email</th>
        <th>add ratings</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      </thead>
      <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.text %><% link_to 'View Ratings', new_topic_post_comment_user_comment_rating_path(@topic, @post, comment) %></td>
          <td><%= comment.user.present? ? comment.user.email : 'No user id' %>
           <td> <%= form_for([@topic, @post, comment, UserCommentRating.new], url: topic_post_comment_user_comment_ratings_path(comment.post.topic, comment.post, comment), remote: true )do |f| %>
               <%= f.hidden_field :comment_id, value: comment.id %>
               <div class="form-group">
                 <%= f.label :value %>
                 <%= f.select :value, (1..5).to_a, prompt: 'Select a rating' %>
               </div>

               <%= f.submit 'Rate Comment', class: 'btn btn-primary'%>
             <% end %></td>


          <td><%= link_to "Show", topic_post_comment_path(@topic, @post, comment) %></td>
          <td><%= link_to "Edit", edit_topic_post_comment_path(@topic, @post, comment) %></td>
          <td><%= button_to "Delete", topic_post_comment_path(@topic, @post, comment), method: :delete %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    No comments
  <% end %>
</div>
<br>

<%= link_to "Back to post", request.referer, class: "btn btn-secondary" %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Back to comments", topic_post_comments_path(@topic,@post,@comments) %>
</div>

app/views/comments/ratings.html.erb
<h1>Ratings for Comment</h1>
<ul>
  <% @comment.user_comment_ratings.each do |rating| %>
    <li><%= rating.user.email %> rated <%= rating.rating %> stars</li>
  <% end %>
</ul>
<%= link_to "Back to Comments", topic_post_comments_path(@topic, @post), class: "btn btn-secondary" %>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <% if can? :edit, @comment %>
    <%= link_to 'Edit comment', edit_topic_post_comment_path(@topic,@post,@comment) %>
  <% end %>

  <%= link_to "View Ratings", comment_ratings_topic_post_comment_path(@topic, @post,@comment), class: "btn btn-info" %>

  <%= button_to "Destroy this comment", topic_post_comment_path(@topic,@post,@comment), method: :delete %>

  <%= link_to "Back to comments", topic_post_comments_path(@topic,@post,@comment), class: "btn btn-secondary" %>
</div>