config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # resources :users, only: [:show]
  #devise_for :users, controllers: { sessions: 'users/sessions' }
  get'/posts' , to: 'posts#all_posts' , as: 'all_posts'
  root  to:'topics#index'
  resources :topics do
    resources :posts do
      patch 'mark_as_read', on: :member
      resources :comments do
        resources :user_comment_ratings
      end
      resources :ratings, only: [:create]
    end
  end
  resources :tags do
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments , dependent: :destroy
  has_many :post_tags
  has_many :tags, through: :post_tags
  paginates_per 3
  has_many :ratings ,dependent: :destroy
  has_one_attached :image
  has_many :posts_users_read_statuses
  has_many :readers, through: :posts_users_read_statuses, source: :user
  def marked_as_read?(user)
    readers.includes([:readers]).include?(user)
  end

  def mark_as_read(user)
    posts_users_read_statuses.find_or_create_by(user: user).update(read: true)
  end

  scope :filter_by_date, ->(from_date, to_date) {
    where(created_at: from_date.beginning_of_day..to_date.end_of_day)
  }

  after_create :update_rating_average
  def update_rating_average
    update_column(:rating_average, ratings.average(:value))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include CanCan::ControllerAdditions
  load_and_authorize_resource
  before_action :set_topic ,except: :all_posts
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # GET /topics/:topic_id/posts or /topics/:topic_id/posts.json
  def index
    @posts = @topic.posts.page(params[:page]).per(3)
    #@comments =Comment.where(post_id: @posts.pluck(:id))
    #@average_ratings = Hash[Rating.group(:post_id).average(:value).map { |k, v| [k, v.round(1)] }]
  end

  def all_posts
    from_date = params[:from_date].presence || 1.day.ago.to_date
    to_date = params[:to_date].presence || Date.today

    from_date = Date.parse(from_date.to_s)
    to_date = Date.parse(to_date.to_s)

    # @posts = Post.left_joins(:ratings, :comments)
    #              .includes([:topic])
    #              .includes([:tags])
    #              .select('posts.*, AVG(ratings.value) as average_rating, COUNT(comments.id) as comments_count')
    #               .group('posts.id')
    #              .filter_by_date(from_date, to_date)
    #              .page(params[:page]).per(10)
    @posts=Post.includes([:topic],[:tags])
               .filter_by_date(from_date, to_date)
               .page(params[:page]).per(10)

  end

  def mark_as_read
    @post = Post.find(params[:id])
    @post.mark_as_read(current_user) if user_signed_in?

    respond_to do |format|
      format.js
    end
  end
  # GET /topics/:topic_id/posts/1 or /topics/:topic_id/posts/1.json
  def show
    @topic = Topic.find(params[:topic_id])
    @posts = @topic.posts.find(params[:id])
    if user_signed_in? && !@post.marked_as_read?(current_user)
      # Mark the post as read
      @post.mark_as_read(current_user)
    end
    @ratings = @post.ratings.group(:value).count
  end

  # GET /topics/:topic_id/posts/new
  def new
    @post = @topic.posts.new

  end

  # GET /topics/:topic_id/posts/1/edit
  def edit

  end

  def create
    #@post = @topic.posts.new(post_params)
    @topic = Topic.find(params[:topic_id]) # Assuming you already have this line to set the topic
    @post = @topic.posts.build(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html{redirect_to  topic_posts_path(@topic, @post), notice: 'Post was successfully created.'}
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to params[:referrer] || topic_post_url(@topic, @post), notice: 'Post was successfully updated.' }

      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/:topic_id/posts/1 or /topics/:topic_id/posts/1.json
  def destroy
    @post.ratings.destroy_all
    @post.tags.clear
    @post.destroy

    respond_to do |format|
      format.html { redirect_to  request.referer || topic_posts_path(@topic), notice: "Post was successfully destroyed." }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_post
    # @post = @topic.posts.find(params[:id])
    @post = Post.find(params[:id])
  end
  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :topic_id,:user_id , :referrer,:image, tag_ids: [])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@topic, @post], id: 'form',local: false ) do |form| %>
  <%= hidden_field_tag :referrer, request.referer %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <%= render "image_preview", form: form, post: @post %>

  <div>
    <%= form.label :tag_ids, "Tags :" %>
    <% Tag.all.each do |tag| %>
      <%= form.check_box :tag_ids, { multiple: true, class: "form-check-input" }, tag.id, nil %>
      <%= label_tag "post_tag_ids_#{tag.id}", tag.name, class: "form-check-label" %>
    <% end %>
  </div>
  <br>
  <%= link_to "Create new tags", new_tag_path %>

  <div class="form-actions">
    <%= form.submit "Save Post" %>
  </div>
<% end %>

<!--<script>-->
<!--    function submitForm() {-->
<!--        var csrfToken = $('meta[name=csrf-token]').attr('content');-->
<!--        var formData = $('#form').serialize();  // Serialize the form data-->

<!--        $.ajax({-->
<!--            url: "/topics/<%= @topic.id %>/posts",-->
<!--            type: "POST",-->
<!--            headers: {-->
<!--                'X-CSRF-Token': csrfToken-->
<!--            },-->
<!--            data: formData,  // Include the serialized form data-->
<!--            success: function(response) {-->
<!--                window.location.href = "<%= topic_posts_path(@topic) %>";-->
<!--                console.log("Post is created");-->

<!--            },-->
<!--            error: function(error) {-->
<!--                console.error("Error marking post as read");-->
<!--            }-->
<!--        });-->
<!--    }-->
<!--</script>-->

app/views/posts/_image_preview.html.erb
<div  data-controller="previews" class="form-group">
  <%= form.label :image %>


  <%= form.file_field :image,
                      direct_upload:true,
                      data:{previews_target:"input",action: "change->previews#preview"},
                      class: "form-control" %>

  <% if @post.image.attached? %>
    <%= image_tag @post.image,data: { previews_target: "preview"},class: "image"%>
  <%else %>
    <%= image_tag "",data: { previews_target: "preview"},class: "image"%>
  <%end %>

</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>
<%= image_tag(post.image ,class: "image") %>
  <p>
    <strong>Topic:</strong>
    <%= post.topic_id %>
  </p>

</div>

app/views/posts/all_posts.html.erb
<h1>All Posts</h1>
<%= form_tag(all_posts_path, method: :get) do %>
  <%= label_tag 'From Date:' %>
  <%= date_field_tag 'from_date', params[:from_date] %>

  <%= label_tag 'To Date:' %>
  <%= date_field_tag 'to_date', params[:to_date] %>

  <%= submit_tag 'Show Details' %>
<% end %>

<table class="table table-hover" style="width:100%;">
  <thead> <!-- Use thead for table headers -->
  <tr>
    <th>No</th>
    <th>Post (Topic)</th>
    <th>Description</th>
    <th>Status</th>
    <th>Created at</th>
    <th>Average Rating</th>
    <th>comments count</th>
    <th>Tags</th>
    <th>Comments</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody> <!-- Use tbody for table body -->
  <% offset = (params[:page].to_i - 1) * @posts.current_per_page + 1 %>
  <% offset = 1 if offset < 1 %> <!-- Ensure offset starts at 1 on the first page -->
  <% @posts.each do |post| %>
    <tr>
      <td><%= offset %></td>
      <td><%= "#{post.title} (#{post.topic.title})" %></td>
      <td><%= post.content %></td>
      <td><%= post.marked_as_read?(current_user) ? 'Read' : 'Unread' %></td>
      <td><%= post.created_at.to_date %></td>
      <td><%= post.rating_average.present? ? " #{post.rating_average.round(1)} Ratings" : 'N/A' %></td>
      <td><%= post.comments_count %></td>
      <td>
        <% if post.tags.any? %>
          <% post.tags.each do |tag| %>
            <%= tag.name %>
          <% end %>
        <% else %>
          No tags added
        <% end %>
      </td>
      <td><%= link_to "Show ", topic_post_comments_path(post.topic, post) %></td>
      <td><%= link_to "Edit", edit_topic_post_path(post.topic, post) %></td>
      <td>
        <% button_to "Delete", topic_post_path(post.topic, post), method: :delete, data: { confirm: "Are you sure?" } %>
        <%= button_to "Delete", topic_post_path(post.topic, post), method: :delete, data: { confirm: "Are you sure?", referrer: request.original_url } %>

      </td>
    </tr>
    <% offset += 1 %>
  <% end %>
  </tbody>
</table>
<%= paginate @posts %>

<%= link_to "Back to Home", root_path, class: "btn btn-secondary" %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>
<%= link_to "Back to post", request.referer, class: "btn btn-secondary" %>

app/views/posts/index.html.erb
<h1>Posts in <%= @topic.title %> Topic</h1>


<%= link_to "New Post", new_topic_post_path, class: "btn btn-secondary" %>
<br>
<br>

<table class="table table-hover" style="width:100%;">
  <thead> <!-- Use thead for table headers -->
  <tr>
    <th>Post</th>
    <th>Description</th>
    <th>Status</th>
    <th>Average Rating</th>
    <th>Comments count</th>
    <th>show</th>
    <th>Comments</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  <% @posts.each do |post| %>

      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= post.marked_as_read?(current_user) ? 'Read' : 'Unread' %></td>
      <td><%= post.rating_average.present? ? " #{post.rating_average.round(1)} Ratings" : 'N/A' %></td>
      <td><%= post.comments_count %></td>
      <td> <%= link_to "Show ", topic_post_path(@topic, post) %></td>
      <td> <%= link_to "show " ,topic_post_comments_path(@topic, post) %> </td>
      <td>  <%= link_to "Edit", edit_topic_post_path(@topic, post) %></td>
      <td><%= button_to "Delete",topic_post_path(@topic, post), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
  <% end %>
    </tbody>
</table>
<%= paginate @posts %>

<%= link_to "Back to Topics", topics_path, class: "btn btn-secondary" %>

app/views/posts/index.js.erb
alert('Post created successfully');
window.location.href = '<%= topic_posts_path(@topic) %>';

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to "Back to Posts", topic_posts_path(@topic), class: "btn btn-secondary" %>

app/views/posts/new.js.erb
<% if @post.errors.any? %>
// Handle errors, for example, display them in an alert
alert("Post creation failed: <%= j @post.errors.full_messages.join(', ') %>");
<% else %>
// Handle successful creation, for example, display a success message
alert("Post created successfully");
// You can also redirect or perform other actions here
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<p><strong>user email : </strong><%= @post.user.present? ? @post.user.email : 'No user id' %></p>

<script>
    $(document).ready(function() {
        // Check if the user is logged in
        var loggedIn = <%= user_signed_in? %>;

        // Make an AJAX call to mark the post as read if the user is logged in
        if (loggedIn) {
            var csrfToken = $('meta[name=csrf-token]').attr('content');

            $.ajax({
                url: "/topics/<%= @topic.id %>/posts/<%= @post.id %>/mark_as_read",
                type: "PATCH",
                headers: {
                    'X-CSRF-Token': csrfToken
                },
                success: function(response) {
                    console.log("Post marked as read");
                    // You can update the UI as needed
                },
                error: function(error) {
                    console.error("Error marking post as read");
                }
            });
        }
    });
</script>

<!-- Display read/unread status -->
<p><strong>Status:</strong> <%= @post.marked_as_read?(current_user) ? 'Read' : 'Unread' %></p>


<% if @post.image.attached? %>
  <%= image_tag(@post.image, class: "image") %>
<%else %>
  <strong>No images added</strong>
<% end %>
<br><br>
<h2>Tags:</h2>
<% if @post.tags.any? %>
  <% @post.tags.each do |tag| %>
    <%= tag.name %>
  <% end %>
<% else %>
  No tags available for this post.
<% end %>
<br><br>

<!-- Display existing user_comment_ratings -->
<h2>Ratings:</h2>
<ul>
  <% @ratings.each do |star, count| %>
    <li><%= star %> Star Ratings: <%= count %></li>
  <% end %>
</ul>

<!-- Rating form -->
<%= form_for([@topic, @post, @post.ratings.build]) do |f| %>
  <%= f.label :value %>
  <%= f.radio_button :value, 1 %> 1 Star
  <%= f.radio_button :value, 2 %> 2 Stars
  <%= f.radio_button :value, 3 %> 3 Stars
  <%= f.radio_button :value, 4 %> 4 Stars
  <%= f.radio_button :value, 5 %> 5 Stars
  <%= f.submit "Submit Rating" %>
<% end %>
<br>
<% if can? :edit, @post %>
  |  <%= link_to 'Edit Post', edit_topic_post_path(@topic,@post) %>  |
<% end %>
|  <%= link_to "show comments" ,topic_post_comments_path(@topic,@post)  %>  |
<%= button_to "Delete", topic_posts_path(@topic), method: :delete, data: { confirm: "Are you sure?" } %><br/>
<%= link_to "Back", topic_posts_path(@topic, @post), class: "btn btn-secondary" %>